# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cpu_stat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cpu_stat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63pu_stat.proto\x12\rmonitor.proto\"\x92\x01\n\x07\x43puStat\x12\x13\n\x0b\x63pu_percent\x18\x02 \x01(\x02\x12\x15\n\rcpu_logic_num\x18\n \x01(\x05\x12\x1d\n\x15\x63pu_physical_core_num\x18\x0b \x01(\x05\x12\x18\n\x10\x63pu_used_percent\x18\x0c \x01(\x02\x12\"\n\x1a\x65\x61\x63h_core_utilization_rate\x18\r \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cpu_stat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CPUSTAT']._serialized_start=34
  _globals['_CPUSTAT']._serialized_end=180
# @@protoc_insertion_point(module_scope)
