# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login_register.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'login_register.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14login_register.proto\x12\rmonitor.proto\"/\n\x0bUserMessage\x12\x13\n\x0b\x61\x63\x63ount_num\x18\x01 \x01(\t\x12\x0b\n\x03pwd\x18\x02 \x01(\t\"G\n\x13UserResponseMessage\x12\x14\n\x0cresponse_str\x18\x01 \x01(\t\x12\x1a\n\x12machine_name_array\x18\x02 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_register_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERMESSAGE']._serialized_start=39
  _globals['_USERMESSAGE']._serialized_end=86
  _globals['_USERRESPONSEMESSAGE']._serialized_start=88
  _globals['_USERRESPONSEMESSAGE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
