# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitor_info.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'monitor_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import net_info_pb2 as net__info__pb2
import mem_info_pb2 as mem__info__pb2
import cpu_stat_pb2 as cpu__stat__pb2
import cpu_softirq_pb2 as cpu__softirq__pb2
import cpu_load_pb2 as cpu__load__pb2
import gpu_info_pb2 as gpu__info__pb2
import time_pb2 as time__pb2
import query_pb2 as query__pb2
import login_register_pb2 as login__register__pb2
import hard_disk_pb2 as hard__disk__pb2
import os_pb2 as os__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12monitor_info.proto\x12\rmonitor.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0enet_info.proto\x1a\x0emem_info.proto\x1a\x0e\x63pu_stat.proto\x1a\x11\x63pu_softirq.proto\x1a\x0e\x63pu_load.proto\x1a\x0egpu_info.proto\x1a\ntime.proto\x1a\x0bquery.proto\x1a\x14login_register.proto\x1a\x0fhard_disk.proto\x1a\x08os.proto\"\x85\x03\n\x0bMonitorInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x02os\x18\x02 \x01(\x0b\x32\x11.monitor.proto.OS\x12*\n\thard_disk\x18\x03 \x01(\x0b\x32\x17.monitor.proto.HardDisk\x12(\n\x08\x63pu_load\x18\x04 \x01(\x0b\x32\x16.monitor.proto.CpuLoad\x12(\n\x08\x63pu_stat\x18\x05 \x01(\x0b\x32\x16.monitor.proto.CpuStat\x12(\n\x08mem_info\x18\x06 \x01(\x0b\x32\x16.monitor.proto.MemInfo\x12(\n\x08net_info\x18\x07 \x01(\x0b\x32\x16.monitor.proto.NetInfo\x12(\n\x08gpu_info\x18\x08 \x03(\x0b\x32\x16.monitor.proto.GpuInfo\x12\x12\n\naccountnum\x18\t \x01(\t\x12!\n\x04time\x18\n \x01(\x0b\x32\x13.monitor.proto.Time\x12\x14\n\x0cmachine_name\x18\x0b \x01(\t2\xa6\x01\n\x0eMonitorManager\x12\x46\n\x0eSetMonitorInfo\x12\x1a.monitor.proto.MonitorInfo\x1a\x16.google.protobuf.Empty\"\x00\x12L\n\x0eGetMonitorInfo\x12\x1b.monitor.proto.QueryMessage\x1a\x1b.monitor.proto.QueryResults\"\x00\x32`\n\x0bUserManager\x12Q\n\rLoginRegister\x12\x1a.monitor.proto.UserMessage\x1a\".monitor.proto.UserResponseMessage\"\x00\x42\x03\x80\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\000'
  _globals['_MONITORINFO']._serialized_start=240
  _globals['_MONITORINFO']._serialized_end=629
  _globals['_MONITORMANAGER']._serialized_start=632
  _globals['_MONITORMANAGER']._serialized_end=798
  _globals['_USERMANAGER']._serialized_start=800
  _globals['_USERMANAGER']._serialized_end=896
# @@protoc_insertion_point(module_scope)
