# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cpu_softirq.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cpu_softirq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63pu_softirq.proto\x12\rmonitor.proto\"\xb0\x01\n\x07SoftIrq\x12\x0b\n\x03\x63pu\x18\x01 \x01(\t\x12\n\n\x02hi\x18\x02 \x01(\x02\x12\r\n\x05timer\x18\x03 \x01(\x02\x12\x0e\n\x06net_tx\x18\x04 \x01(\x02\x12\x0e\n\x06net_rx\x18\x05 \x01(\x02\x12\r\n\x05\x62lock\x18\x06 \x01(\x02\x12\x10\n\x08irq_poll\x18\x07 \x01(\x02\x12\x0f\n\x07tasklet\x18\x08 \x01(\x02\x12\r\n\x05sched\x18\t \x01(\x02\x12\x0f\n\x07hrtimer\x18\n \x01(\x02\x12\x0b\n\x03rcu\x18\x0b \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cpu_softirq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOFTIRQ']._serialized_start=37
  _globals['_SOFTIRQ']._serialized_end=213
# @@protoc_insertion_point(module_scope)
