# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpu_info.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gpu_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egpu_info.proto\x12\rmonitor.proto\"\xd3\x01\n\x07GpuInfo\x12\n\n\x02id\x18\n \x01(\t\x12\x10\n\x08gpu_name\x18\x01 \x01(\t\x12\x15\n\rgpu_mem_total\x18\x02 \x01(\x05\x12\x14\n\x0cgpu_mem_free\x18\x03 \x01(\x05\x12\x14\n\x0cgpu_mem_used\x18\x04 \x01(\x05\x12\x17\n\x0fgpu_mem_utilize\x18\x05 \x01(\x05\x12\x13\n\x0bgpu_utilize\x18\x06 \x01(\x05\x12\x12\n\ntemperture\x18\x07 \x01(\x05\x12\x11\n\tfan_speed\x18\x08 \x01(\x05\x12\x12\n\npower_stat\x18\t \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpu_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPUINFO']._serialized_start=34
  _globals['_GPUINFO']._serialized_end=245
# @@protoc_insertion_point(module_scope)
