# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import login_register_pb2 as login__register__pb2
import monitor_info_pb2 as monitor__info__pb2
import query_pb2 as query__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in monitor_info_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MonitorManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMonitorInfo = channel.unary_unary(
                '/monitor.proto.MonitorManager/SetMonitorInfo',
                request_serializer=monitor__info__pb2.MonitorInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMonitorInfo = channel.unary_unary(
                '/monitor.proto.MonitorManager/GetMonitorInfo',
                request_serializer=query__pb2.QueryMessage.SerializeToString,
                response_deserializer=query__pb2.QueryResults.FromString,
                _registered_method=True)


class MonitorManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetMonitorInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitorInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMonitorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMonitorInfo,
                    request_deserializer=monitor__info__pb2.MonitorInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMonitorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitorInfo,
                    request_deserializer=query__pb2.QueryMessage.FromString,
                    response_serializer=query__pb2.QueryResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitor.proto.MonitorManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('monitor.proto.MonitorManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitorManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetMonitorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.proto.MonitorManager/SetMonitorInfo',
            monitor__info__pb2.MonitorInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.proto.MonitorManager/GetMonitorInfo',
            query__pb2.QueryMessage.SerializeToString,
            query__pb2.QueryResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoginRegister = channel.unary_unary(
                '/monitor.proto.UserManager/LoginRegister',
                request_serializer=login__register__pb2.UserMessage.SerializeToString,
                response_deserializer=login__register__pb2.UserResponseMessage.FromString,
                _registered_method=True)


class UserManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoginRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoginRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginRegister,
                    request_deserializer=login__register__pb2.UserMessage.FromString,
                    response_serializer=login__register__pb2.UserResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitor.proto.UserManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('monitor.proto.UserManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoginRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.proto.UserManager/LoginRegister',
            login__register__pb2.UserMessage.SerializeToString,
            login__register__pb2.UserResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
